<div class="center">
    <?php if ($this->cursor['previous']) : ?>
        <div class="pagination">
            <a class="btn btn-default" href="/tweets?cursor=<?php echo $this->cursor['previous']; ?>">Previous Page</a>
        </div>
    <?php endif; ?>

    <?php if ($this->cursor['next']) : ?>
        <div class="pagination">
            <a class="btn btn-default" href="/tweets?cursor=<?php echo $this->cursor['next']; ?>">Next Page</a>
        </div>
    <?php endif; ?>
</div>
